<a href="https://colab.research.google.com/github/Elizabeth2061/Laboratory-work/blob/main/%D0%9B%D0%A04_%D0%9F%D1%80%D1%83%D0%B4%D0%BA%D0%B0_%D0%84_%D0%9E.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Прудка Єлизавета Олександрівна
Лабораторна 4.
Група 2-8.
Варіант 26.

1. Знайти матрицю С = АВ - ВА

In [ ]:
import numpy as np
a = np.matrix([[1, 2], [4, -1]])
b = np.matrix([[2, -3], [-4, 1]])
ab = np.dot(a, b)
ba = np.dot(b, a)
c = ab - ba
print("Матриця С:")
print(c)

Матриця С:
[[ 4 -8]
 [12 -4]]


2. Піднести матрицю до степеня.

In [ ]:
a = np.array([[-1, 2], [0, 1]])
c = a^2
print("Піднесення матриці до 2го степеня:")
print(c)

Піднесення матриці до 2го степеня:
[[-3  0]
 [ 2  3]]


3. Знайти добуток матриць.

In [ ]:
a = np.matrix([[3, 5], [6, -1]])
b = np.matrix([[2, 1], [-3, 2]])
c = np.dot(a, b)
print("Добуток матриць:")
print(c)

Добуток матриць:
[[-9 13]
 [15  4]]


4. Обчислити визначник.

In [ ]:
a = np.array([[2, 3, 4], [1, 0, 6], [7, 8, 9]])
a_det = np.linalg.det(a)
print("Визначник матриці:")
print(a_det.round(2))

Визначник матриці:
35.0


5. Обчислити визначник.

In [ ]:
a = np.array([[1, 2, 3, 4], [-2, 1, -4, 3], [3, -4, -1, 2], [4, 3, -2, -1]])
a_det = np.linalg.det(a)
print("Визначник матриці:")
print(a_det.round(2))

Визначник матриці:
900.0


6. Знайти обернену матрицю.

In [ ]:
a = np.matrix([[1, 2, -3], [0, 1, 2], [0, 0, 1]])
a_inv = np.linalg.inv(a)
print("Обернена матриця:")
print(a_inv)

Обернена матриця:
[[ 1. -2.  7.]
 [ 0.  1. -2.]
 [ 0.  0.  1.]]


7. Визначити ранг матриці.

In [ ]:
a = np.array([[1, 2, 3, 4], [3, -1, 2, 5], [1, 2, 3, 4], [1, 3, 4, 5]])
rank = np.linalg.matrix_rank(a)
print("Ранг матриці:")
print(rank)

Ранг матриці:
2


8. Розв’язати систему лінійних рівнянь.
Варіант 26.

In [ ]:
# Матричний метод
def matrix_method(coefficients, constants):
    inverse_matrix = np.linalg.inv(coefficients)
    return np.dot(inverse_matrix, constants)

# Метод Крамера
def cramer_method(coefficients, constants):
    det_coefficients = np.linalg.det(coefficients)
    solutions = []
    for i in range(len(coefficients)):
        modified_coefficients = np.copy(coefficients)
        modified_coefficients[:, i] = constants
        solutions.append(round(np.linalg.det(modified_coefficients) / det_coefficients, 1))
    return solutions

#Метод Гауса
def gauss_method(a, b):
    n = len(b)

    for k in range(0, n-1):
        for i in range(k+1, n):
            if a[i, k] != 0.0:
                lam = a[i, k] / a[k, k]
                a[i, k+1:n] = a[i, k+1:n] - lam * a[k, k+1:n]
                b[i] = b[i] - lam * b[k]

    x = np.zeros(n)
    for k in range(n-1, -1, -1):
        x[k] = (b[k] - np.dot(a[k, k+1:n], x[k+1:n])) / a[k, k]

    return x

def main():
    a = np.array([[1.0, 2.0, -1.0],
                  [3.0, 4.0, 1.0],
                  [5.0, 1.0, -3.0]])

    b = np.array([-3.0, 1.0, -2.0])

    # Матричний метод
    x_matrix = matrix_method(a, b)
    print("Матричний метод:", x_matrix)

    # Метод Крамера
    x_cramer = cramer_method(a, b)
    print("Метод Крамера:", x_cramer)

    # Метод Гауса
    x_gauss = gauss_method(a, b)
    print("Метод Гауса:", x_gauss)


if __name__ == "__main__":
    main()

Матричний метод: [ 1. -1.  2.]
Метод Крамера: [1.0, -1.0, 2.0]
Метод Гауса: [ 1. -1.  2.]


#Завдання 2.
 3.Створіть прямокутну матрицю A, яка має N рядків і M стовпців з
випадковими елементами. Визначте середні значення для всіх рядків і
стовпців матриці.

In [ ]:
import numpy as np

N = 4
M = 5

# Створення матриці A розміром N x M з випадковими елементами
A = np.random.randint(1, 9, size=(N, M))

print("Матриця A:")
print(A)

# Обчислення середніх значень для кожного рядка
row_means = A.mean(axis=1)
print("\nСередні значення для кожного рядка:")
print(row_means)

# Обчислення середніх значень для кожного стовпця
col_means = A.mean(axis=0)
print("\nСередні значення для кожного стовпця:")
print(col_means)


Матриця A:
[[6 6 2 1 8]
 [3 8 6 1 8]
 [6 6 8 2 5]
 [6 3 4 6 5]]

Середні значення для кожного рядка:
[4.6 5.2 5.4 4.8]

Середні значення для кожного стовпця:
[5.25 5.75 5.   2.5  6.5 ]
